---
# tasks file for send_logs
- name: send logs to s3
  block:
    - name: Intsall the latest version of apache
      yum:
        name: httpd
        state: latest

    - name:  start httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: remove index
      file:
        path: /var/www/html/index.html
        state: absent


    - name: add index
      file:
        path: /var/www/html/index.html
        state: touch

    - name: add line in file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> I did it <h1>

    - name: python and pip install
      yum:
        name:
          - python
          - pip
    - name: make sure install boto, boto3, and botocore
      pip:
        name: "{{ item }}"
      loop:
        - boto
        - boto3
        - botocore
    - name: save folder name
      set_fact:
        folder_name: "{{ hostvars[inventory_hostname]['public_dns_name']}}"

    - name: create folder s3
      aws_s3:
        bucket: joconnor-logs
        mode: create
        object: "{{ folder_name }}"
    - name: deposit error log in s3
      aws_s3:
        bucket: joconnor-logs
        mode: put
        object: "{{ folder_name }}/error_log"
        src: "/etc/httpd/logs/error_log"




