---
# 
- name: Intsall the latest version of apache
  yum:
    name: httpd
    state: latest

- name:  start httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: remove index
  file:
    path: /var/www/html/index.html
    state: absent


- name: add index
  file:
    path: /var/www/html/index.html
    state: touch

- name: add line in file
  lineinfile:
    path: /var/www/html/index.html
    line: <h1> {{myName}} did it <h1>

